# Generated by Django 4.2 on 2023-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
